### ISSUE TITLE
lora微调完，在inference的时候会出现一直重复输出的情况。

### ISSUE THREAD

**Issue by lindongs** [FreddyBanana/ChatGLM2-LoRA-Trainer#1]
我怀疑是在训练时加载dataset的时候tokenzer，input_ids好像最后没有加结束标签。我不知道是不是我理解的问题。
def process_data(args, tokenizer, dataset):
    data = dataset.shuffle().map(
        lambda data_point: tokenizer(
            generate_prompt(args, data_point),
            truncation=True,
            max_length=args.CUTOFF_LEN,
            padding="max_length",
        )
    )
    return data
    这里解析出来的data['train'][1]['input_ids']最后的ids不是eos。希望得到博主的指点

**Comment by FreddyBanana** [comment]
我调的没有这个问题呀，
你可以加add_eos_token=True试一下。
我看其它训练ChatGLM的代码都没有加这个，所以我也没加...
也可能是其它地方的问题，你的学习率调了多少，不要调太大了。

**Comment by FreddyBanana** [comment]
确实有这个问题，但是我这边只出现在最后一个保存模型上，前面的checkpoint都没问题...
不知道是不是保存的代码有问题...
我把最终模型的保存代码改成 trainer.save_model(args.OUTPUT_DIR + "/model_final")了，看看有没有效果。
然后，add_eos_token=True我也加上了，看看能不能解决问题。
大概周一出结果~

**Comment by FreddyBanana** [comment]
结果出来了，加了add_eos_token=True依然有这个问题。
我再找找怎么解决吧...😑

**Comment by lindongs** [comment]
感谢博主，我结合了之前chatglm1的lora微调的，我换了一种处理ids的方式，手动加了一个结束的ids，发现可以了

**Comment by FreddyBanana** [comment]
okok~
本仓库也手动加eos_token_id了，效果还在测试~
